Downgrade to std@0.92.0
std@0.99.0 had errors

pault@debian:~/Dev/Personal/dnt$ deno upgrade --version 1.10.3
Checking https://github.com/denoland/deno/releases/download/v1.10.3/deno-x86_64-unknown-linux-gnu.zip
30.3 MiB / 30.3 MiB (100.0%)
Deno is upgrading to version 1.10.3
Archive:  /tmp/.tmp3V16L0/deno.zip
  inflating: deno
Upgraded successfully
pault@debian:~/Dev/Personal/dnt$ dnit test
Check file:///home/pault/Dev/Personal/dnt/main.ts
error: TS18022 [ERROR]: A method cannot be named with a private identifier.
  #tryGrowByReslice(n: number) {
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.99.0/io/buffer.ts:85:3